### ISSUE TITLE
Web Scrape Academic Calendar

### ISSUE THREAD

**Issue by AbigailMedina** [Apexal/late#173]
Write something to scrape the academic calendar to get monday=tuesdays and/or breaks

**Comment by Apexal** [comment]
https://info.rpi.edu/registrar/academic-calendar

**Comment by Apexal** [comment]
So I experimented for a few hours with a RSS or JSON feed that RPI provides for events on the calendar but it appears broken. Thanks RPI.

It seems like good ol' web scraping will have to suffice.

**Comment by Apexal** [comment]
Turns out there is a "Export Calendar as iCal" option [here](http://events.rpi.edu/cal/calendar/showCalendarForExport.rdo;jsessionid=1ED2E1A59E8C95249EDC4A206F660116) which can be used to grab the events.

For now I've settled with LATE displaying the Academic Calendar events on the Dashboard calendar: ![screenshot](https://snag.gy/2XgTSe.jpg)

Clicking on an academic calendar event opens a simple modal with the full text, date range, and a link to the actual event page.
