### ISSUE TITLE
Design dashboard

### ISSUE THREAD

**Issue by AbigailMedina** [Apexal/late#23]
- Determine what info to show (separate from About page)
- Edit `/views/home/index.pug`
- Edit `/client/sass/routes/home.scss`

**Comment by Apexal** [comment]
@AbigailMedina 	how is this going so far?

**Comment by ksanusi** [comment]
Dashboard is currently empty. Should we move the calendar view and make that the dashboard?

**Comment by Apexal** [comment]
The assignment calendar view should stay under the assignments view since it only shows due dates.

The dashboard will also have a calendar view, except it will be a weekAgenda view and will show the users' work/study schedule along with the exact due dates of assignments. Since we don't have that data yet, it is hard to start the dashboard, though the skeleton for it can be started.

@ksanusi
