### ISSUE TITLE
Recurring Assignments

### ISSUE THREAD

**Issue by arachiele** [Apexal/late#251]
Often classes have recurring assignments due weekly or biweekly. Instead of manually entering the same assignments, can LATE have an option for this? Conceptually similar to Google Calendar “Repeat” function, repeating an assignment every week, class, every other week, etc.

**Comment by Apexal** [comment]
This has been requested by a few people now. I can't think of a perfect way to implement this. The problem is how to display repeated assignments. If a user adds a repeating weekly assignment, we can easily add copies of it up until the end of the semester, but then that totally clutters the Upcoming Assignments view (especially when grouping by course).

We'll have to limit Upcoming Assignments to like 2 weeks in the future, and display far away assignments below the main view.

**Comment by Apexal** [comment]
You can now copy assignments, but there should still be a clear way to create recurring assignments.

**Comment by Apexal** [comment]
This now works, but if you accidentally add a bunch of assignments on the wrong day there is no easy way to delete them all.

When a recurring assignment is deleted, the user should be prompted to either delete that specific one or all the recurring ones (e.g. as Google Calendar handles repeating events)
