### ISSUE TITLE
Merge assignments and exams

### ISSUE THREAD

**Issue by AbigailMedina** [Apexal/late#292]
Problem:
Users don't like using the exam interface for "upcoming/previous/calendar exams ". It is too separated from the assignments, giving an unclear idea of how much work the user has this upcoming week. 

Solution:
I would like the upcoming/previous/calendar exam dropdown to be merged with the assignments equivalent so that all assignments and exams can be seen in the same interface. The front end routes that are currently "assignments/upcoming" and "exams/upcoming" should be "/upcoming" and similarly set for other routes in the dropdown.

Notes:
In order to distinguish exams from assignments on these various pages, there should be a distinguishing font awesome icon on exams. Current options considered are exclamation-triangle, radiation-alt, skull-crossbones, or dumpster-fire.

**Comment by Apexal** [comment]
Great work so far @AbigailMedina and @kvverti 

I checked out your progress and I'm glad to say its a big improvement, having one single place for both types of assessments. I saw some places where you were struggling with Vue so I spent some time yesterday and today filling in some of those places.

Here are also some things to note:
- in the backend we will use `assessment` to mean assignment or exam, but in the frontend we should refrain from using that term as its ambiguous. Instead we should use "Coursework" instead of "Assessments". As for a single assessment, I'm not sure which other word would cover this. We'll discuss tomorrow.
- I compromised on the routes as I saw you went with the `/assessments/:assessmentID` route and that makes it difficult to tell the assessmentType and determine what to display. I made the routes now be `/assessments/a/:assignmentID` and `/assessments/e/:examID` which actually resembles the backend routes.
- I reworked AssessmentsOverview so that there is a single `assessment` that is grabbed instead of having a separate `exam` and `assignment` data object that only one of which is used


There are still a few bugs that I'd like you two to work through tomorrow, as well as finish the display and presentation of the combined pages.
