### ISSUE TITLE
Admin Student List Improvements

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#395]
- [x] pagination
- [x] searching
- [x] filtering

**Comment by robere2** [comment]
In terms of how pagination, searching, and filtering should work, I think the logic should be done on the back end rather than front end. This adds delay between switching pages and searches, but less overhead on initial load or the memory in the browser. This is what I have been working on so far however I want to confirm we're on the same page (hah.) before getting too far ahead.

Note that as a result, sorting would also have to be moved to the back end.

**Comment by Apexal** [comment]
That's exactly how I envisioned it! Awesome work so far.
