### ISSUE TITLE
Improve Buefy Header

### ISSUE THREAD

**Issue by zacharylove** [Apexal/late#413]
The new Buefy header does not currently support hover dropdown or direct links on dropdown parents. For example, if one wanted to access a tool, you would need to click on the header option to open the dropdown before selecting the tool, and it is not currently possible to access the tools index from a non-mobile device.

Additionally, the mobile navigation menu has reverted back to its original state- no additional stylings, online count visible, and unable to collapse dropdowns.

<img width="370" alt="Screen Shot 2019-09-16 at 7 34 24 PM" src="https://user-images.githubusercontent.com/12072877/65000296-0f5fd980-d8b9-11e9-8a1d-c4b99ca5acf0.png">

**Comment by zacharylove** [comment]
I'm currently going to restore the previous functionality (while keeping Buefy), and push the updated version directly to master. It's important to both accessibility and our design to have these features available.

**Comment by zacharylove** [comment]
Update: Navbar currently looks like this on development:
<img width="1440" alt="Screen Shot 2019-09-16 at 7 47 06 PM" src="https://user-images.githubusercontent.com/12072877/65000837-27d0f380-d8bb-11e9-964a-e337a4fc1e62.png">

Currently looking into it.

**Comment by Apexal** [comment]
We can added mobile dropdown toggling on our own, we did not have that prior to using Buefy's navbar. I refactored this to use Buefy as some people, you included, pointed out how clicking on a menu item did not dismiss it; this is fixed with Buefy's navbar.

Definitely go ahead and return the mobile border and similar but just be wary of the amount of custom CSS used for it; it shouldn't take much and we don't want to make it brittle

**Comment by zacharylove** [comment]
Cool, we'll just need to push some changes through to fix it up. Buefy's "hoverable" property restores dropdown-on-hover functionality, and we'll need some JS to get collapsible menus available on mobile.
