### ISSUE TITLE
Remove lectures from schedule during finals

### ISSUE THREAD

**Issue by bertrk** [Apexal/late#530]
Currently, the schedule shows lectures as occurring until the last day of finals. I think this could be improved by removing them after the last day of classes, and maybe showing when reading days are. 

This a bit more in-depth, but it would also be cool to display finals as actual blocks of time on the calendar since lectures won't be there.

**Comment by Apexal** [comment]
This should not happen as we keep track of a term's last class day. Looks like I forgot to include this limit in some places! Where exactly did you see this?

**Comment by bertrk** [comment]
I'm looking specifically at the week of December 15-20 on the calendar. Class blocks stop showing up on the Friday, but Monday-Thursday are finals only (and presumably the week before has a reading day or two).  
![finals_LATE](https://user-images.githubusercontent.com/55285622/69173019-ef24e480-0acc-11ea-84d2-65135466c5d3.png)

**Comment by tobiasjpark** [comment]
@Apexal  how are we currently keeping track of a term's last class day (is there a variable stored somewhere)? And where is this supposed to be enforced?

I looked in DashboardCalendar.vue and on line 122 it specifies the "end" for "validRange" using the variable  this.$store.getters.currentTerm.end ; I'm not sure if that is where the problem is (does that variable store the end of the entire term or is that the variable that stores the end of classes?) 

Other than that, is there anywhere else you suggest I should be looking for the problem?

**Comment by tobiasjpark** [comment]
There might still be a slight issue with this, now LATE is not showing courses on Wednesday the 11th even though there is technically still class that day (that is the last day of classes).

**Comment by Apexal** [comment]
I believe this is because `currentTerm.classesEnd` is the date without a time, therefore it means the very start of the day. We should use `moment(this.currentTerm.classesEnd).endOf('day')` instead.

**Comment by kd2eom** [comment]
Fixed with 32ddaa2
