### ISSUE TITLE
Course Work Blocks

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#532]
Currently work blocks must be associated with a specific assessment. Students should be able to schedule a time to just study for a course in general.

**Comment by tobiasjpark** [comment]
Backend file to modify: /server/api/blocks/blocks.model.js
Set _assesment.required=false so that it is possible to not have work block associated with specific assignment.
Add another course property that is same as assesment but points to course (that way work block can point to course generally), and have it required that either _assesment or the course property is set.

Then modify frontend, which currently uses _assesment to display courses and must be modified to be able to display courses that have only the course property set.

**Comment by kd2eom** [comment]
<div
        v-for="c in courses"
        :key="c.crn"
        class="panel-block"
      >
        {{ c.title }}
      </div>

For displaying work blocks in frontend
Add an @click on-click event to make it do stuff....
